### PR TITLE
Switched openUDID generation to use CFUUID instead of [NSProcessInfo glob

### PR DESCRIPTION
**Pull request by akrapacs**
Switched openUDID generation to use CFUUID instead of [NSProcessInfo globallyUniqueString]

### CODE REVIEW

**Comment by ylechelle** [comment]
it's all pretty random and unique in the end no? once hashed with md5, we get little collisions either way.

**Comment by jessearmand** [comment]
The CFUUID string needs to be hashed as well with 4 random bytes added to it.

**Comment by ylechelle** [comment]
Guys, I still haven't merged that pull request - I need more arguments in favor of using CFUUID over [NSProcessInfo globallyUniqueString]... why not use both methods randomly at the same time to add more spice?

**Comment by lhunath** [comment]
Because the NSProcessInfo stuff is hacky and clumsy?

**Comment by jessearmand** [comment]
From the docs of NSProcessInfo.
Global ID for the process. The ID includes the host name, process ID, and a time stamp, which ensures that the ID is "unique for the network".

It's not guaranteed to be unique to the computer.

**Comment by pal** [comment]
This is done, no? Close the issue?

**Comment by ylechelle** [comment]
indeed

**Comment by ylechelle** [comment]
Not quite. The pull request is incorrect in terms of reformatting. But the core argument stands. Need to use CFUUID vs.  [NSProcessInfo globallyUniqueString] - will get to it within 24h.

**Pull request closed without merging**
