### PR TITLE
Back-Off Persistence Via Keychain

### PR DESCRIPTION
**Pull request by thanatos0801**
Added back-off persistence via device keychain.  This handles the case when all OpenUDID apps are uninstalled and then one gets reinstalled.

### CODE REVIEW

**Comment by ylechelle** [comment]
Hello Josh,
I want to integrate this, but it needs to be redone to merge with the recent priority changes.
1/ integration is the right way to go
2/ but the wrapper needs to be modified/refactored and be prefixed with OUDID_ to make sure that it doesn't conflict with other wrappers if OUDID is included in libraries, etc... 
Would you take care of redoing it from the main branch?
Thanks.

**Comment by thanatos0801** [comment]
Yann,

Sure, can do…  I'm stepping out for vacation just now.  I'll see if I can get it from the hotel tonight.

# -Josh

# == Chance favors the prepared mind...

**Comment by ylechelle** [comment]
Great! No rush I suppose… 
Have a great vacation either way.

**Comment by andrejvanderzee** [comment]
Hi,

Shouldn't the following be added to the keychain?

[keychain setObject:kSecAttrAccessibleAlwaysThisDeviceOnly forKey:kSecAttrAccessible];

If I understand correctly, this enforces the OpenUDID to be removed after a restore on a different device.

When will the keychain be merged to the main branch?

**Pull request closed without merging**
