### PR TITLE
Switched BundleId to use GUUID

### PR DESCRIPTION
**Pull request by anupamtulsyan**
using guuid instead of bundle id to identify each within a device. This will prevent other developers to access the pasteboard and see what app user has installed.

### CODE REVIEW

**Comment by ylechelle** [comment]
Actually, the point of the bundle ID was to let other developers create an app that would essentially provide a UI for users to opt out of certain apps.
If the bundle ID is obsfucated, then it's impossible for anyone to create an app that lists current apps using OpenUDID on the device, and opt-out of one or more apps.
So this fix somehow brings the implementation closer to the original uniqueIdentifier, accessible by all, and not facilitating the discrete opt-out process. So it's a step-back re: the original specs (that wanted to do good by the user). No?

**Comment by anupamtulsyan** [comment]
I think opt out process should be specific to an app. So, the developer who integrates open udid should give an option to user if he wants to opt out rather than creating a generic app for opt out. Also, there can still be a feature where user can opt-out of all apps.

**Comment by ylechelle** [comment]
I'm not sure I trust that all developers would in fact implement this in their UI, do you? ;-)
Using your mechanism, it is true that one cannot discretely opt-out (i.e. discriminating one-by-one and by name), it's all or nothing... is this what you mean?

**Comment by tomhubina** [comment]
ylechelle - if your concern is regarding developers doing "bad" things, then you should consider the bad things that can be done with things the way they are. If someone forks the existing code base and everyone else out there is using the code as it stands today ...
1. Use the GUID mechanism to hide their presence, prevent end users from blocking them with apps, and still gain the benefits of OpenUUID for install tracking.
2. Don't insert their own data into the pastebook, just mine it for data to track application installs and removals across the entire ecosystem, mine that for specific player behaviors, etc. Disguise that in some other free utility application that gains additional personal identifying information and you have a massively valuable and totally invasive data warehouse to tap into.
3. For the more cutthroat areas out there a malicious developer could ignore using OpenUUID for their own tracking, and just consume the data to do things like:
   - Detect which competitors have apps installed on their players device, and when those apps were installed
   - Tailor their offerings to their users to promote their other titles, "Hey .. you like Game X, you probably would like our Game Y a lot better!"
   - Incentivize players to uninstall competitor apps by tracking when a specific app is removed from the pastebook, "I see you have App X installed .. delete it and we'll give you some cool thing!"

Also, as a potential final nail in the coffin - Unless there's some kind of mandatory central registry, I think an end user will only be able to disable applications on an app by app basis after the fact (have to know which one to disable, and you don't know what they are till the tracking has already occurred on first launch) which I think will ultimately defeat any attempts at per-application tracking disabling.

I think you're FAR better off exposing as little as you can and having a global, "Disable all please, thank you!" that the end users can trigger. BTW - if that's desired (and I tend to think it's a good idea), then we need to be able to determine that the user has disabled the tracking so we can instruct advertisers not to show them offers and such that rely on the tracking.

**Comment by ylechelle** [comment]
yes, yes, I'm with you both ;-)

**Comment by ylechelle** [comment]
Done!

**Comment by anupamtulsyan** [comment]
thnks!

**Comment by jamesrz2live** [comment]
Just wanted to point out that the GUID generated for the application is never saved to the user defaults. Therefore, every time the user runs an application with OpenUDID it will generate a new application GUID (and therefore a new UDID). I've submitted a fix in pull request [#16](https://github.com/ylechelle/OpenUDID/pull/16).

**Comment by ylechelle** [comment]
Also, I think we introduced a new problem here: every time the app is removed and reinstalled, it creates a new UIPasteboard slot. Here's what I suggest... we use a hashed version of the bundleid, or (oh no!) a hashed version of the MAC address. These are fixed items that remain within the device, and not used for the ultimate OpenUDID key.... what do you think?

**Comment by anupamtulsyan** [comment]
Even if he the app is re installed with a new guuid it will pick up
the right udid based on frequency. The only issue i see is with opt
out. For that user if he has previously opted out and then re
installed the app opt out fails.

I think if we want to solve this we will need to use hashed version of
bundle id. If mac address is used then all the apps will write the
same value in all the slots?? There will be no differentiator for
apps. am i missing something??

On Mar 30, 2012, at 7:29 AM, Yann Lechelle
reply@reply.github.com
wrote:

**Comment by ylechelle** [comment]
the problem here is not the UDID - indeed, it will be picked up.
the problem is with 100 UIPasteboardS: if the guid is new, then we will create A NEW PASTEBOARD CLONE for no good reason:

```   OpenUDIDLog(@"Available Slot %@ Existing Slot %@",availableSlotPBid,myRedundancySlotPBid);
    if (availableSlotPBid!=nil && (myRedundancySlotPBid==nil || [availableSlotPBid isEqualToString:myRedundancySlotPBid])) {
#if TARGET_OS_IPHONE || TARGET_IPHONE_SIMULATOR
        UIPasteboard\* slotPB = [UIPasteboard pasteboardWithName:availableSlotPBid create:YES];
        [slotPB setPersistent:YES];

```

```

**Comment by tomhubina** [comment]
If you store a hash of the bundle id, it's still going to be unique per game, which means it has all the same problems as storing the bundle id.

If OpenUDID includes that Mac address, then putting some computed value on the pasteboard is completely pointless. Just use the Mac address everywhere and be done with it.

As for the growth of the pasteboard, I was under the impression that when you uninstall an application that anything it added to the pasteboard is removed. As I recall, that's the whole reason why each app has a unique entry on the pasteboard. With that in mind, how can an app have more than one entry on the pasteboard?

**Comment by ylechelle** [comment]
Tom,

Indeed, let's forget about the MAC, and the hashed bundle id. Doesn't work.

I think I found an acceptable solution, which hopefully doesn't open another corner-case loop-hole.
What if we use the UIPasteboards not as a scarce resource, but rather like a FIFO queue.
In the event an app somehow regenerates its key (GID), then it adds another Pasteboard if an empty one is available, and if not, it overrides the oldest one.

What do you think?

**Comment by tomhubina** [comment]
That sounds fine .. but you lose the ability to disable tracking on individual apps (something I personally think isn't very valuable, and hard to achieve anyway).

Does it makes sense that each app should automatically regenerate its GID if its missing and put itself back in the queue? The pasteboard would continuously cycle once you had more apps than the FIFO depth .. dunno if that's good or bad, or if it even matters. It feels like a moving target might be "good" from an obfuscation standpoint, but I have nothing to back that up. _shrug_

**Pull request merged**
